// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package json;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:json.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required float value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>required float value = 1;</code>
   * @return The value.
   */
  float getValue();

  /**
   * <code>required int64 currency = 2;</code>
   * @return Whether the currency field is set.
   */
  boolean hasCurrency();
  /**
   * <code>required int64 currency = 2;</code>
   * @return The currency.
   */
  long getCurrency();
}
