// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package json;

public final class TransactionProtos {
  private TransactionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_json_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_json_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_json_Statistic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_json_Statistic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_json_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_json_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\004json\".\n\013Transaction\022\r\n" +
      "\005value\030\001 \002(\002\022\020\n\010currency\030\002 \002(\003\"\'\n\tStatis" +
      "tic\022\n\n\002id\030\001 \002(\t\022\016\n\006client\030\002 \001(\003\"@\n\006Resul" +
      "t\022\016\n\006client\030\001 \002(\003\022&\n\013transaction\030\002 \002(\0132\021" +
      ".json.TransactionB\025B\021TransactionProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_json_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_json_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_json_Transaction_descriptor,
        new java.lang.String[] { "Value", "Currency", });
    internal_static_json_Statistic_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_json_Statistic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_json_Statistic_descriptor,
        new java.lang.String[] { "Id", "Client", });
    internal_static_json_Result_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_json_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_json_Result_descriptor,
        new java.lang.String[] { "Client", "Transaction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
